F
======================================================================
FAIL: test_main_loop (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_4.py", line 12, in test_main_loop
    self.assertEqual(
AssertionError: None != '¡Buenas tardes Anibal!\naloh\nacav\noso\n¡Bonita palabra!\nAdios Anibal'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)